-- MySQL Script generated by MySQL Workbench
-- Wed Dec 27 13:13:08 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema futsal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `futsal` ;

-- -----------------------------------------------------
-- Schema futsal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `futsal` DEFAULT CHARACTER SET utf8 COLLATE utf8_czech_ci ;
USE `futsal` ;

-- -----------------------------------------------------
-- Table `futsal`.`region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`region` ;

CREATE TABLE IF NOT EXISTS `futsal`.`region` (
  `regionId` INT NOT NULL AUTO_INCREMENT,
  `regionName` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`regionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`playground`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`playground` ;

CREATE TABLE IF NOT EXISTS `futsal`.`playground` (
  `playgroundId` INT NOT NULL AUTO_INCREMENT,
  `playgroundName` VARCHAR(100) NOT NULL,
  `managerName` VARCHAR(45) NOT NULL,
  `managerSurname` VARCHAR(45) NOT NULL,
  `managerPhone` VARCHAR(45) NOT NULL,
  `managerEmail` VARCHAR(45) NOT NULL,
  `regionId` INT NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `postcode` VARCHAR(10) NOT NULL,
  `note` VARCHAR(255) NULL,
  PRIMARY KEY (`playgroundId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`arbiter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`arbiter` ;

CREATE TABLE IF NOT EXISTS `futsal`.`arbiter` (
  `arbiterId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `postcode` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`arbiterId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`team` ;

CREATE TABLE IF NOT EXISTS `futsal`.`team` (
  `teamId` INT NOT NULL AUTO_INCREMENT,
  `teamName` VARCHAR(255) NOT NULL,
  `ownerName` VARCHAR(255) NOT NULL,
  `ownerSurname` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `postcode` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `registrationDate` DATETIME NOT NULL,
  `code` VARCHAR(255) NOT NULL,
  `logo` VARCHAR(255) NOT NULL DEFAULT 'photos/teams/no_photo_available.jpg',
  PRIMARY KEY (`teamId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`season`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`season` ;

CREATE TABLE IF NOT EXISTS `futsal`.`season` (
  `seasonId` INT NOT NULL AUTO_INCREMENT,
  `seasonName` VARCHAR(45) NOT NULL,
  `actual` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`seasonId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`match` ;

CREATE TABLE IF NOT EXISTS `futsal`.`match` (
  `matchId` INT NOT NULL AUTO_INCREMENT,
  `visitorsId` INT NOT NULL,
  `homeId` INT NOT NULL,
  `round` INT NOT NULL,
  `matchDate` DATETIME NOT NULL,
  `seasonId` INT NOT NULL,
  `played` TINYINT(1) NOT NULL DEFAULT 0,
  `playgroundId` INT NULL,
  `arbiterId` INT NULL,
  `visitorGoals` INT NULL,
  `homeGoals` INT NULL,
  PRIMARY KEY (`matchId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`player`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`player` ;

CREATE TABLE IF NOT EXISTS `futsal`.`player` (
  `playerId` INT NOT NULL AUTO_INCREMENT,
  `teamId` INT NOT NULL,
  `registrationDate` DATETIME NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `surname` VARCHAR(255) NOT NULL,
  `birthdate` DATETIME NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `postcode` VARCHAR(10) NOT NULL,
  `photo` VARCHAR(255) NOT NULL DEFAULT 'photos/players/NoPhoto.jpg',
  PRIMARY KEY (`playerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`matchParticipant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`matchParticipant` ;

CREATE TABLE IF NOT EXISTS `futsal`.`matchParticipant` (
  `matchParticipantId` INT NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `goals` INT NOT NULL DEFAULT 0,
  `redCard` TINYINT(1) NOT NULL DEFAULT 0,
  `yellowCard` TINYINT(1) NOT NULL DEFAULT 0,
  `isKeeper` TINYINT(1) NOT NULL DEFAULT 0,
  `releasedGoals` INT NOT NULL DEFAULT 0,
  `matchId` INT NOT NULL,
  `teamId` INT NOT NULL,
  `seasonId` INT NOT NULL,
  PRIMARY KEY (`matchParticipantId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`payment` ;

CREATE TABLE IF NOT EXISTS `futsal`.`payment` (
  `paymentId` INT NOT NULL AUTO_INCREMENT,
  `playerId` INT NOT NULL,
  `purpose` VARCHAR(255) NOT NULL,
  `sum` INT NOT NULL,
  `dueDate` DATETIME NOT NULL,
  `payedOn` DATETIME NULL,
  `variableSymbol` VARCHAR(10) NOT NULL,
  `seasonId` INT NOT NULL,
  `teamId` INT NOT NULL,
  PRIMARY KEY (`paymentId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `futsal`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `futsal`.`user` ;

CREATE TABLE IF NOT EXISTS `futsal`.`user` (
  `login` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

COMMIT;
